export interface MgmtQuestion {
  id: number;
  part: number;
  partName: string;
  grade: string;
  topic: string;
  question: string;
  choices: [string, string, string, string];
  answer: 0 | 1 | 2 | 3;
  explanation: string;
  source?: string;
}

export const managementQuestions: MgmtQuestion[] = [
  {
    id: 1, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전관리목적',
    question: '교통안전관리의 궁극적 목표로 가장 적절한 것은?',
    choices: ['복지사회의 실현', '주택보급 확대만', '교통수송량의 무조건적 증가', '여가시설 확대만'],
    answer: 0,
    explanation: '2020.11 복원 오답노트에서 교통수송량 증가는 목표가 아니며 궁극적으로 복지사회 실현을 지향하는 축이 확인된다.',
    source: '기출복원',
  },
  {
    id: 2, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전관리자직무',
    question: '교통안전관리자의 직무에 해당하지 않는 것으로 복원된 것은?',
    choices: ['교통안전관리 업무 수행', '교통수단 및 운영체계 개선을 직접 권고하는 업무', '안전업무 점검', '사고예방 관련 관리'],
    answer: 1,
    explanation: '공개 오답노트에서 \'교통수단 및 교통수단운영체계의 개선 권고\'를 직무가 아닌 선지로 기억하고 있다.',
    source: '기출복원',
  },
  {
    id: 3, part: 2, partName: '조직·평가', grade: 'A', topic: '교통안전조직',
    question: '교통안전조직에 관한 설명 중 부적절한 관점은?',
    choices: ['구성원의 공헌의욕이 필요하다', '인간을 단순히 목적달성의 수단으로만 보는 것', '의사소통이 중요하다', '공통목표가 필요하다'],
    answer: 1,
    explanation: '안전조직은 사람을 단순 도구로만 보지 않는다는 취지의 복원축이다.',
    source: '기출복원',
  },
  {
    id: 4, part: 2, partName: '조직·평가', grade: 'A', topic: '현장안전회의',
    question: '현장안전회의(Tool Box Meeting)에 관한 설명으로 옳지 않은 것은?',
    choices: ['짧고 집중적으로 진행한다', '장시간 진행하는 회의가 원칙이다', '현장 위험요인을 확인한다', '작업 전 안전의식을 환기한다'],
    answer: 1,
    explanation: '현장안전회의는 짧고 실질적인 안전확인을 위한 소집단 회의이므로 장시간 회의라는 설명이 틀린 축으로 복원됐다.',
    source: '기출복원',
  },
  {
    id: 5, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '교통사고 피해자와 가족의 정신적 고통을 금전적으로 평가한 비용은?',
    choices: ['교통지체비', '고통비용(위자료)', '연료손실비', '차량수리비'],
    answer: 1,
    explanation: '2020.11 복원에서 정신적 고통의 보상 개념을 고통비용/위자료로 구분하는 문제가 확인된다.',
    source: '기출복원',
  },
  {
    id: 6, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '초기·우발·마모 고장으로 고장률 변화를 설명하는 이론은?',
    choices: ['욕조곡선', 'MBO', '파레토 법칙', '하인리히 도미노'],
    answer: 0,
    explanation: '부품의 결함·노화와 우발고장을 시간축으로 설명하는 욕조곡선이 직접 복원됐다.',
    source: '기출복원',
  },
  {
    id: 7, part: 1, partName: '관리이론', grade: 'A', topic: '파욜 관리5요소',
    question: '파욜의 경영관리 활동에 해당하는 묶음은?',
    choices: ['예산-회계-조달-운송-판매', '계획-채용-보상-광고-감사', '계획-조직-지휘-조정-통제', '조직-홍보-판매-통계-징계'],
    answer: 2,
    explanation: '2020.11 복원에서 계획·조직·지휘·조정·통제를 관리활동으로 묻는 문제가 확인된다.',
    source: '기출복원',
  },
  {
    id: 8, part: 3, partName: '운전행동', grade: 'A', topic: '반응시간',
    question: '단순반응시간의 의미는?',
    choices: ['둘 이상의 자극 중 하나를 선택하는 시간', '하나의 자극에 하나의 반응을 하는 데 걸리는 시간', '차량이 완전히 정지할 때까지의 시간', '암순응에 필요한 시간'],
    answer: 1,
    explanation: '단순반응시간은 하나의 자극-하나의 반응 상황으로 복원됐다.',
    source: '기출복원',
  },
  {
    id: 9, part: 1, partName: '관리이론', grade: 'A', topic: '소집단교육기법',
    question: '10명 이하 소집단 교육기법으로 보기 어려운 것은?',
    choices: ['토의법', '역할연기', '카운슬링', '브레인스토밍'],
    answer: 2,
    explanation: '2020.11 복원에서 카운슬링을 소집단 교육기법과 구분하는 문제가 확인된다.',
    source: '기출복원',
  },
  {
    id: 10, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '참가자가 자유롭게 아이디어를 내고 제안 과정에서 비판을 금지하는 기법은?',
    choices: ['브레인스토밍', '델파이법', '직무순환', '카운슬링'],
    answer: 0,
    explanation: '자유로운 의견제시와 비판금지를 핵심으로 하는 브레인스토밍 문제가 복원됐다.',
    source: '기출복원',
  },
  {
    id: 11, part: 2, partName: '조직·평가', grade: 'A', topic: '갈등해소',
    question: '갈등 당사자가 직접 대면해 원인을 함께 해결하는 방법은?',
    choices: ['단순 분리', '문제해결법', '회피', '강압'],
    answer: 1,
    explanation: '대면적 화합을 통한 갈등해소 방법을 문제해결법으로 묻는 문제가 확인된다.',
    source: '기출복원',
  },
  {
    id: 12, part: 5, partName: '사고분석', grade: 'B', topic: '교통사고요인',
    question: '교통기관의 3대 요소는?',
    choices: ['통로·사용자·운임', '운반구·운임·광고', '통로·운반구·동력', '사용자·광고·동력'],
    answer: 2,
    explanation: '공유 복원은행에서 교통기관의 구성요소를 묻는 문항이 확인된다.',
    source: '기출복원',
  },
  {
    id: 13, part: 5, partName: '사고분석', grade: 'B', topic: '교통사고요인',
    question: '교통사고의 대표적 3대 원인 축에 포함되지 않는 것은?',
    choices: ['차량 요인', '문화적 요인', '도로·환경 요인', '인적 요인'],
    answer: 1,
    explanation: '복원은행은 인적·차량·환경 축과 다른 항목을 구분하도록 묻는다.',
    source: '기출복원',
  },
  {
    id: 14, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '교통안전관리 목표로 보기 어려운 것은?',
    choices: ['안전한 교통체계', '사고 예방', '수송량 증가 그 자체', '인명·재산 보호'],
    answer: 2,
    explanation: '수송량 증가는 안전관리의 직접 목표가 아니라는 반복축이다.',
    source: '기출복원',
  },
  {
    id: 15, part: 2, partName: '조직·평가', grade: 'A', topic: '비공식조직',
    question: '비공식 조직에 대한 설명으로 틀린 것은?',
    choices: ['인간관계가 중요하다', '공식조직과 병존할 수 있다', '자연발생할 수 있다', '목적의식이 전혀 없다'],
    answer: 3,
    explanation: '비공식 조직도 구성원 간 공통관심이나 목적이 있을 수 있다.',
    source: '기출복원',
  },
  {
    id: 16, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '관련 없는 평가항목을 비슷하게 평가하는 오류는?',
    choices: ['투사', '상관적 편견', '현혹효과', '상동적 오류'],
    answer: 1,
    explanation: '상관적 편견은 무관한 평가항목 간 상관성을 과도하게 인식하는 오류다.',
    source: '기출복원',
  },
  {
    id: 17, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '한 특성에 대한 좋은 인상이 전체 평가를 좋게 만드는 오류는?',
    choices: ['투사', '현혹효과', '중심화 경향', '상동적 오류'],
    answer: 1,
    explanation: '현혹효과(halo effect)의 전형적 정의다.',
    source: '기출복원',
  },
  {
    id: 18, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '소속 집단의 고정관념으로 개인을 판단하는 오류는?',
    choices: ['현혹효과', '상동적 오류', '투사', '관대화 경향'],
    answer: 1,
    explanation: '개인의 실제 특성보다 집단에 대한 선입견으로 판단한다.',
    source: '기출복원',
  },
  {
    id: 19, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '자신의 특성을 타인에게 있다고 보는 평가오류는?',
    choices: ['상동적 오류', '현혹효과', '상관적 편견', '투사'],
    answer: 3,
    explanation: '자기 특성을 상대에게 전가하는 것이 투사다.',
    source: '기출복원',
  },
  {
    id: 20, part: 4, partName: '심리·동기', grade: 'A', topic: '교수설계',
    question: '교수설계의 분석단계에 해당하지 않는 것은?',
    choices: ['요구분석', '시청각 매체·보조자료의 실제 개발', '직무분석', '학습자 분석'],
    answer: 1,
    explanation: '매체 개발은 분석단계보다는 설계·개발 과정에 가깝다.',
    source: '기출복원',
  },
  {
    id: 21, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '교통사고 예방을 위해 안전관리 규정을 만드는 접근은?',
    choices: ['생리적 접근', '제도적 접근', '차량공학적 접근', '관리적 접근'],
    answer: 1,
    explanation: '법·규정·제도를 통한 예방을 제도적 접근으로 구분한다.',
    source: '기출복원',
  },
  {
    id: 22, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '통계·품질관리·경영관리 기법을 활용하는 접근은?',
    choices: ['제도적 접근', '형사적 접근', '관리적 접근', '순수 생리적 접근'],
    answer: 2,
    explanation: '관리기법으로 사고유형과 원인을 분석하는 접근이다.',
    source: '기출복원',
  },
  {
    id: 23, part: 3, partName: '운전행동', grade: 'A', topic: '시야각',
    question: '약 100km/h 주행 시 시야각 복원값으로 알려진 것은?',
    choices: ['약 180도', '약 120도', '약 40도', '약 5도'],
    answer: 2,
    explanation: '공유 복원은행에서 100km/h 주행 시 약 40도 축이 제시된다.',
    source: '기출복원',
  },
  {
    id: 24, part: 3, partName: '운전행동', grade: 'A', topic: '동체시력',
    question: '동체시력은 정지시력보다 어느 정도 감소하는 것으로 복원됐는가?',
    choices: ['약 60% 증가', '약 30%', '약 5%', '변화 없음'],
    answer: 1,
    explanation: '공유 복원은행의 반복 숫자축이다.',
    source: '기출복원',
  },
  {
    id: 25, part: 4, partName: '심리·동기', grade: 'A', topic: '매슬로우 욕구단계',
    question: '매슬로우 욕구단계의 순서는?',
    choices: ['안전-생리-사회-자아실현-존중', '사회-안전-생리-존중-자아실현', '생리-안전-사회-존중-자아실현', '생리-사회-안전-존중-자아실현'],
    answer: 2,
    explanation: '욕구단계 순서 문제가 공유 복원은행에 포함됐다.',
    source: '기출복원',
  },
  {
    id: 26, part: 3, partName: '운전행동', grade: 'A', topic: '정보처리순서',
    question: '운전자의 정보처리 순서로 옳은 것은?',
    choices: ['지각-식별-판단-행동', '판단-지각-행동-식별', '행동-판단-지각-식별', '식별-행동-지각-판단'],
    answer: 0,
    explanation: '지각에서 행동으로 이어지는 순서형 문제가 반복된다.',
    source: '기출복원',
  },
  {
    id: 27, part: 4, partName: '심리·동기', grade: 'A', topic: '캇츠 태도기능',
    question: '캇츠가 말한 태도의 기능 중 자기 정체성과 가치관을 표현하는 것은?',
    choices: ['지식 기능', '가치표현 기능', '자아방어 기능', '도구적 기능'],
    answer: 1,
    explanation: '가치표현 기능을 직접 묻는 복원축이다.',
    source: '기출복원',
  },
  {
    id: 28, part: 1, partName: '관리이론', grade: 'A', topic: '3E 안전대책',
    question: '3E에 포함되지 않는 것은?',
    choices: ['Effort', 'Engineering', 'Education', 'Enforcement'],
    answer: 0,
    explanation: '안전대책 3E를 구분하는 문제다.',
    source: '기출복원',
  },
  {
    id: 29, part: 1, partName: '관리이론', grade: 'A', topic: 'RAMS',
    question: 'RAMS의 구성으로 옳은 것은?',
    choices: ['Reliability-Availability-Maintainability-Safety', 'Risk-Action-Management-Service', 'Rule-Availability-Monitoring-System', 'Reliability-Accuracy-Mobility-Safety'],
    answer: 0,
    explanation: 'RAMS 약어 조합 문제가 공유 복원은행에 있다.',
    source: '기출복원',
  },
  {
    id: 30, part: 3, partName: '운전행동', grade: 'A', topic: 'IPDE',
    question: 'IPDE의 순서로 옳은 것은?',
    choices: ['Identify-Predict-Decide-Execute', 'Identify-Predict-Detect-Escape', 'Identify-Plan-Drive-Evaluate', 'Inspect-Predict-Direct-Execute'],
    answer: 0,
    explanation: '위험인지·예측·결정·실행 순서다.',
    source: '기출복원',
  },
  {
    id: 31, part: 2, partName: '조직·평가', grade: 'A', topic: '중간관리자',
    question: '중간관리자의 역할로 보기 어려운 것은?',
    choices: ['부서 간 조정', '현장 최일선 직접감독만 수행', '상하 조정', '소관부문 종합관리'],
    answer: 1,
    explanation: '중간관리층과 일선감독층의 역할을 구분하는 문제다.',
    source: '기출복원',
  },
  {
    id: 32, part: 1, partName: '관리이론', grade: 'A', topic: '소집단교육기법',
    question: '10명 내외 소집단 교육기법으로 보기 어려운 것은?',
    choices: ['역할연기', '토의', '카운슬링', '브레인스토밍'],
    answer: 2,
    explanation: '카운슬링은 개인상담 성격이 강하다는 반복축이다.',
    source: '기출복원',
  },
  {
    id: 33, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '직무와 절차의 표준화·문서화 정도를 뜻하는 것은?',
    choices: ['분권화', '비공식화', '공식화', '전문화'],
    answer: 2,
    explanation: '조직구조의 공식화 개념을 묻는 문제다.',
    source: '기출복원',
  },
  {
    id: 34, part: 2, partName: '조직·평가', grade: 'A', topic: '갈등해소',
    question: '대면을 통해 갈등 당사자가 공동 해결안을 찾는 방법은?',
    choices: ['단순 분리', '회피', '문제해결법', '강압'],
    answer: 2,
    explanation: '대면적 화합과 문제해결법 연결이 반복된다.',
    source: '기출복원',
  },
  {
    id: 35, part: 5, partName: '사고분석', grade: 'B', topic: '안전벨트',
    question: '안전벨트의 기능으로 틀린 것은?',
    choices: ['충돌 시 충격력을 더 크게 만드는 것이 목적이다', '인명피해 감소', '탑승자 이탈 방지', '차내 2차 충돌 감소'],
    answer: 0,
    explanation: '안전벨트의 보호기능을 반대로 제시한 함정이다.',
    source: '기출복원',
  },
  {
    id: 36, part: 3, partName: '운전행동', grade: 'A', topic: '고령자교통특성',
    question: '고령자의 교통행동 특성으로 옳지 않은 것은?',
    choices: ['반응시간 증가 가능', '거리판단 저하 가능', '젊은 사람보다 반응속도가 항상 빠르다', '시각·청각 저하 가능'],
    answer: 2,
    explanation: '노화에 따른 지각·반응 저하를 묻는 문제다.',
    source: '기출복원',
  },
  {
    id: 37, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '개인의 행동·가치 판단에 기준이 되는 집단은?',
    choices: ['사고조사반', '실무위원회', '비공식조직', '준거집단'],
    answer: 3,
    explanation: '준거집단(reference group) 정의 문제다.',
    source: '기출복원',
  },
  {
    id: 38, part: 3, partName: '운전행동', grade: 'A', topic: '암순응',
    question: '암순응에 관한 설명으로 틀린 것은?',
    choices: ['밝은 곳에서 어두운 곳으로 적응', '명순응보다 적응시간이 짧다', '망막의 감광 적응과 관련', '명순응보다 오래 걸리는 편'],
    answer: 1,
    explanation: '공유 복원은행에서 암순응 시간이 더 길다는 축이 반복된다.',
    source: '기출복원',
  },
  {
    id: 39, part: 4, partName: '심리·동기', grade: 'A', topic: '매슬로우 욕구단계',
    question: '매슬로우 욕구 5단계의 순서를 묻는 과정형 문제',
    choices: ['생리-사회-안전-존중-자아실현', '사회-존중-생리-안전-자아실현', '안전-생리-사회-존중-자아실현', '생리-안전-사회-존중-자아실현'],
    answer: 3,
    explanation: '2025.06.27 춘천 후기에서 \'특정 개념의 과정\' 문제 예시로 직접 언급.',
    source: '기출복원',
  },
  {
    id: 40, part: 3, partName: '운전행동', grade: 'A', topic: 'IPDE',
    question: 'IPDE의 순서를 묻는 문제',
    choices: ['Identify-Plan-Decide-Evaluate', 'Identify-Predict-Decide-Execute', 'Inspect-Predict-Drive-Execute', 'Identify-Predict-Detect-Escape'],
    answer: 1,
    explanation: '2025.06.27 후기에서 과정형 출제 예시로 직접 언급.',
    source: '기출복원',
  },
  {
    id: 41, part: 2, partName: '조직·평가', grade: 'A', topic: '현장안전회의',
    question: 'Tool Box Meeting의 순서를 묻는 문제',
    choices: ['위험예지-확인-도입-점검-운행', '도입-점검장비-운행지시-위험예지-확인', '점검-도입-확인-운행-위험예지', '도입-위험예지-점검장비-확인-운행'],
    answer: 1,
    explanation: '2025.06.27 후기에서 과정형 출제 예시로 직접 언급.',
    source: '기출복원',
  },
  {
    id: 42, part: 4, partName: '심리·동기', grade: 'A', topic: '교수설계',
    question: '교수설계의 단계 순서를 묻는 문제',
    choices: ['설계-감사-보상', '평가-분석-통제', '분석-징계-평가', '분석-설계/개발-평가의 흐름'],
    answer: 3,
    explanation: '2025.06 후기에서 교수설계 단계가 실제 출제축으로 언급됐다.',
    source: '기출복원',
  },
  {
    id: 43, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '교통안전관리론에서 함께 출제됐다고 언급된 민간투자 방식은?',
    choices: ['ATO·ATP 구분', 'CBTC·LTE-R 구분', 'CTC·TMS 구분', 'BTO·BTL 관련 구분'],
    answer: 3,
    explanation: '2025.06.28 구로 후기에서 매슬로우와 함께 BTO·BTL 관련 문제가 대표적으로 언급됐다.',
    source: '기출복원',
  },
  {
    id: 44, part: 1, partName: '관리이론', grade: 'A', topic: '4M',
    question: '4M의 네 요소를 구분하는 문제',
    choices: ['Machine-Material-Money-Market', 'Man-Money-Market-Method', 'Man-Media-Motion-Method', 'Man-Machine-Media-Management'],
    answer: 3,
    explanation: '2025.08.25 응시후기에서 4M이 직접 언급.',
    source: '기출복원',
  },
  {
    id: 45, part: 5, partName: '사고분석', grade: 'B', topic: '교통사고요인',
    question: '교통사고 요인을 구분하는 문제',
    choices: ['운임·광고·매출 요인', '보험·세무·정비 요인', '회계·홍보·세무 요인', '인적·차량·도로/환경 요인'],
    answer: 3,
    explanation: '2025.08.25 후기에서 교통사고 요인이 직접 언급.',
    source: '기출복원',
  },
  {
    id: 46, part: 4, partName: '심리·동기', grade: 'A', topic: '캇츠 태도기능',
    question: '캇츠의 태도 기능을 묻는 문제',
    choices: ['BTO·BTL·BOT·BOO만', '계획·조직·지휘·통제만', '신호·제동·가속·운전 기능', '가치표현·도구적·지식·자아방어 기능을 구분'],
    answer: 3,
    explanation: '2025.08.25 후기에서 심리학자 캇츠가 직접 언급.',
    source: '기출복원',
  },
  {
    id: 47, part: 4, partName: '심리·동기', grade: 'A', topic: '교수설계',
    question: '교수설계 3단계를 묻는 문제',
    choices: ['분석-설계-평가', '평가-조직-설계', '분석-보상-평가', '설계-감사-통제'],
    answer: 0,
    explanation: '2025.08.25 후기에서 교수설계 3단계가 직접 언급.',
    source: '기출복원',
  },
  {
    id: 48, part: 3, partName: '운전행동', grade: 'A', topic: '명순응',
    question: '명순응의 방향',
    choices: ['정지물체→이동물체 적응', '어두운 곳→밝은 곳 적응', '원거리→근거리 적응', '밝은 곳→어두운 곳 적응'],
    answer: 1,
    explanation: '2025.08.25 후기에서 명순응·암순응 출제 언급.',
    source: '기출복원',
  },
  {
    id: 49, part: 3, partName: '운전행동', grade: 'A', topic: '암순응',
    question: '암순응의 방향',
    choices: ['청각 자극 적응', '밝은 곳→어두운 곳 적응', '어두운 곳→밝은 곳 적응', '근거리→원거리 적응'],
    answer: 1,
    explanation: '2025.08.25 후기에서 명순응·암순응 출제 언급.',
    source: '기출복원',
  },
  {
    id: 50, part: 1, partName: '관리이론', grade: 'A', topic: '욕조곡선',
    question: '욕조곡선의 순서',
    choices: ['마모-우발-초기', '초기고장-우발고장-마모고장', '우발-초기-마모', '초기-마모-우발'],
    answer: 1,
    explanation: '2025.08.25 후기에서 욕조곡선이 직접 언급.',
    source: '기출복원',
  },
  {
    id: 51, part: 4, partName: '심리·동기', grade: 'A', topic: '내외적요인',
    question: '내적 요인에 해당하는 것',
    choices: ['개인의 동기·태도·성격·능력', '차량 결함', '조직·시설', '날씨·도로상태'],
    answer: 0,
    explanation: '2025.08.25 후기에서 내적·외적 요인 구분이 직접 언급.',
    source: '기출복원',
  },
  {
    id: 52, part: 4, partName: '심리·동기', grade: 'A', topic: '외부자극',
    question: '외부자극의 의미',
    choices: ['조직 규정 그 자체', '기억 속에서만 생기는 정보', '개인의 성격 자체', '환경에서 감각기관으로 들어오는 정보'],
    answer: 3,
    explanation: '2025.08.25 후기에서 외부자극이 직접 언급.',
    source: '기출복원',
  },
  {
    id: 53, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '개인의 태도·가치·행동판단 기준이 되는 집단',
    choices: ['준거집단', '공식위원회', '사고조사반', '기술위원회'],
    answer: 0,
    explanation: '2025.08.25 후기에서 준거집단이 직접 언급.',
    source: '기출복원',
  },
  {
    id: 54, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전관리목적',
    question: '다음 중 교통안전관리 목적에 대한 설명으로 가장 적절한 것은?',
    choices: ['교통량 자체의 최대화', '운송원가만 절감', '홍보성과 극대화', '교통사고 예방과 인명·재산 피해 최소화'],
    answer: 3,
    explanation: '안전관리의 본질은 사고 예방과 생명·재산 보호다.',
    source: '기출·신경향',
  },
  {
    id: 55, part: 1, partName: '관리이론', grade: 'A', topic: '파욜 관리5요소',
    question: '다음 중 관리 5요소에 대한 설명으로 가장 적절한 것은?',
    choices: ['조직-채용-평가-해고-보상', '예산-집행-감사-징계-보고', '계획-평가-홍보-보상-통계', '계획-조직-지휘-조정-통제'],
    answer: 3,
    explanation: '파욜의 대표적 관리과정 5요소다.',
    source: '기출·신경향',
  },
  {
    id: 56, part: 2, partName: '조직·평가', grade: 'A', topic: '공식화',
    question: '다음 중 공식화에 대한 설명으로 가장 적절한 것은?',
    choices: ['전문화 수준', '권한 위임 정도', '비공식 의사소통 정도', '직무 규칙과 절차를 표준화·문서화하는 정도'],
    answer: 3,
    explanation: '공식화는 규칙·절차의 문서화와 표준화를 뜻한다.',
    source: '기출·신경향',
  },
  {
    id: 57, part: 2, partName: '조직·평가', grade: 'A', topic: '중간관리자',
    question: '다음 중 중간관리자에 대한 설명으로 가장 적절한 것은?',
    choices: ['상하·부서 간 조정과 소관부문 종합관리', '최고경영자의 장기전략만 담당', '현장 최일선 직접감독만 담당', '개별 작업만 수행'],
    answer: 0,
    explanation: '중간관리자는 상하·수평 조정자 역할이 핵심이다.',
    source: '기출·신경향',
  },
  {
    id: 58, part: 5, partName: '사고분석', grade: 'B', topic: '관리적접근',
    question: '다음 중 관리적 접근에 대한 설명으로 가장 적절한 것은?',
    choices: ['시력 개선만으로 예방', '경영·통계·품질관리 기법을 활용한 사고 예방', '도로기하구조만 개선', '법률 제정만으로 예방'],
    answer: 1,
    explanation: '관리적 접근은 조직·통계·품질관리 등을 이용한다.',
    source: '기출·신경향',
  },
  {
    id: 59, part: 5, partName: '사고분석', grade: 'B', topic: '제도적접근',
    question: '다음 중 제도적 접근에 대한 설명으로 가장 적절한 것은?',
    choices: ['보험료만 조정', '운전자 성격만 교정', '차량 성능만 개선', '안전규정과 제도를 정비하여 사고 예방'],
    answer: 3,
    explanation: '규정·법·제도 개선을 통한 예방이다.',
    source: '기출·신경향',
  },
  {
    id: 60, part: 1, partName: '관리이론', grade: 'A', topic: '4M',
    question: '다음 중 4M-Man에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['관리요인', '환경·매개요인', '기계요인', '인간요인'],
    answer: 3,
    explanation: '4M은 Man, Machine, Media, Management다.',
    source: '기출·신경향',
  },
  {
    id: 61, part: 1, partName: '관리이론', grade: 'A', topic: '4M',
    question: '다음 중 4M-Machine에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['운전자 피로', '기계·차량·설비의 결함', '악천후', '안전문화 미흡'],
    answer: 1,
    explanation: 'Machine은 기계·설비 문제다.',
    source: '기출·신경향',
  },
  {
    id: 62, part: 1, partName: '관리이론', grade: 'A', topic: '4M',
    question: '다음 중 4M-Media에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['운전자의 성격', '관리자의 방침', '작업환경·교통환경 등 매개요인', '정비불량만'],
    answer: 2,
    explanation: 'Media는 인간과 기계를 둘러싼 환경·매개 조건이다.',
    source: '기출·신경향',
  },
  {
    id: 63, part: 1, partName: '관리이론', grade: 'A', topic: '4M',
    question: '다음 중 4M-Management에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['인지오류', '브레이크 고장', '악천후', '조직·관리·감독상의 결함'],
    answer: 3,
    explanation: 'Management는 관리체계·감독·절차 문제다.',
    source: '기출·신경향',
  },
  {
    id: 64, part: 5, partName: '사고분석', grade: 'B', topic: '교통사고요인',
    question: '다음 중 교통사고 요인에 대한 설명으로 가장 적절한 것은? [2025.06 후기축]',
    choices: ['인적·재무·홍보 요인', '인적·차량·도로환경 요인', '기계·회계·광고 요인', '세무·예산·정책 요인'],
    answer: 1,
    explanation: '사고 원인은 사람·차량·도로환경의 상호작용으로 본다.',
    source: '기출·신경향',
  },
  {
    id: 65, part: 5, partName: '사고분석', grade: 'B', topic: '하인리히',
    question: '다음 중 하인리히 도미노에 대한 설명으로 가장 적절한 것은?',
    choices: ['연쇄적 원인이 이어져 사고가 발생', '사고는 항상 우연', '사고는 원인이 없다', '모든 사고는 단일 기계결함'],
    answer: 0,
    explanation: '도미노 이론은 사고를 연쇄적 원인 진행으로 설명한다.',
    source: '기출·신경향',
  },
  {
    id: 66, part: 1, partName: '관리이론', grade: 'A', topic: '욕조곡선',
    question: '다음 중 욕조곡선-초기고장기에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['고장률 일정', '초기에 고장률이 높다가 감소', '고장률이 계속 증가', '고장 0'],
    answer: 1,
    explanation: '초기 결함이 제거되며 고장률이 감소한다.',
    source: '기출·신경향',
  },
  {
    id: 67, part: 1, partName: '관리이론', grade: 'A', topic: '욕조곡선',
    question: '다음 중 욕조곡선-우발고장기에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['급격히 증가', '초기 급감', '비교적 일정한 낮은 고장률', '고장 없음'],
    answer: 2,
    explanation: '정상 사용 중 우발고장은 비교적 일정하다.',
    source: '기출·신경향',
  },
  {
    id: 68, part: 1, partName: '관리이론', grade: 'A', topic: '욕조곡선',
    question: '다음 중 욕조곡선-마모고장기에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['노후화로 고장률 증가', '초기불량 제거', '고장률 일정', '고장 0'],
    answer: 0,
    explanation: '마모·노후가 진행되며 고장률이 상승한다.',
    source: '기출·신경향',
  },
  {
    id: 69, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 중 운전자 정보처리에 대한 설명으로 가장 적절한 것은? [2025.06 후기축]',
    choices: ['행동-판단-식별-지각', '식별-지각-행동-판단', '지각-식별-판단-행동', '판단-행동-지각-식별'],
    answer: 2,
    explanation: '운전정보는 지각→식별→판단→행동으로 처리한다.',
    source: '기출·신경향',
  },
  {
    id: 70, part: 3, partName: '운전행동', grade: 'A', topic: '교통안전일반',
    question: '다음 중 주의의 집중에 대한 설명으로 가장 적절한 것은?',
    choices: ['주의가 사라짐', '한 대상에 주의를 모아 다른 자극을 상대적으로 무시', '주의대상을 계속 바꿈', '여러 자극에 주의를 나눔'],
    answer: 1,
    explanation: '한 대상에 선택적으로 집중하는 과정이다.',
    source: '기출·신경향',
  },
  {
    id: 71, part: 3, partName: '운전행동', grade: 'A', topic: '교통안전일반',
    question: '다음 중 주의의 배분에 대한 설명으로 가장 적절한 것은?',
    choices: ['한 자극만 보는 것', '주의 완화만', '주의 중단', '여러 대상에 주의를 적절히 나눔'],
    answer: 3,
    explanation: '주의 배분은 둘 이상의 정보원에 주의를 나누는 것이다.',
    source: '기출·신경향',
  },
  {
    id: 72, part: 3, partName: '운전행동', grade: 'A', topic: '동체시력',
    question: '다음 중 동체시력에 대한 설명으로 가장 적절한 것은?',
    choices: ['청각 거리판단', '암순응 능력', '색채 판별', '움직이는 대상의 세부를 식별하는 시력'],
    answer: 3,
    explanation: '움직이는 물체나 이동 중 대상 식별능력이다.',
    source: '기출·신경향',
  },
  {
    id: 73, part: 3, partName: '운전행동', grade: 'A', topic: '동체시력',
    question: '다음 중 동체시력 감소율에 대한 설명으로 가장 적절한 것은?',
    choices: ['약 60% 증가', '정지시력보다 약 30% 감소', '변화 없음', '약 5% 감소'],
    answer: 1,
    explanation: '공개 복원축에서 약 30% 감소가 반복된다.',
    source: '기출·신경향',
  },
  {
    id: 74, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 중 속도와 시야에 대한 설명으로 가장 적절한 것은? [2025.06 후기축]',
    choices: ['속도가 증가하면 무한히 넓어짐', '서로 무관', '속도 증가 시 암순응 즉시 향상', '속도가 증가하면 유효 시야가 좁아지는 경향'],
    answer: 3,
    explanation: '고속일수록 주변시야가 축소되는 경향이 있다.',
    source: '기출·신경향',
  },
  {
    id: 75, part: 3, partName: '운전행동', grade: 'A', topic: '시야각',
    question: '다음 중 100km/h 시야각에 대한 설명으로 가장 적절한 것은? [복원축]',
    choices: ['약 180도', '약 5도', '약 120도', '약 40도'],
    answer: 3,
    explanation: '공개 정리자료에서 약 40도 축이 반복된다.',
    source: '기출·신경향',
  },
  {
    id: 76, part: 3, partName: '운전행동', grade: 'A', topic: '명순응',
    question: '다음 중 명순응에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['동체시력 향상', '색맹검사', '어두운 곳에서 밝은 곳으로 이동할 때의 적응', '밝은 곳에서 어두운 곳으로 적응'],
    answer: 2,
    explanation: '명순응은 어두움→밝음 적응이다.',
    source: '기출·신경향',
  },
  {
    id: 77, part: 3, partName: '운전행동', grade: 'A', topic: '암순응',
    question: '다음 중 암순응에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['어두운 곳에서 밝은 곳으로 적응', '주변시야 확대', '근거리 초점', '밝은 곳에서 어두운 곳으로 이동할 때의 적응'],
    answer: 3,
    explanation: '암순응은 밝음→어두움 적응이며 보통 더 오래 걸린다.',
    source: '기출·신경향',
  },
  {
    id: 78, part: 3, partName: '운전행동', grade: 'A', topic: '암순응',
    question: '다음 중 명·암순응 관계에 대한 설명으로 가장 적절한 것은?',
    choices: ['암순응이 명순응보다 일반적으로 오래 걸림', '둘 다 적응시간 없음', '명순응이 항상 훨씬 오래 걸림', '둘은 동일'],
    answer: 0,
    explanation: '어두운 환경 적응은 더 오래 걸린다.',
    source: '기출·신경향',
  },
  {
    id: 79, part: 3, partName: '운전행동', grade: 'A', topic: '반응시간',
    question: '다음 중 반응시간에 대한 설명으로 가장 적절한 것은?',
    choices: ['시야 확대시간', '완전 정지까지 제동거리', '자극 인지 후 행동 개시까지 걸리는 시간', '도로폭 판단시간'],
    answer: 2,
    explanation: '자극에서 실제 반응 시작까지의 지연이다.',
    source: '기출·신경향',
  },
  {
    id: 80, part: 3, partName: '운전행동', grade: 'A', topic: 'IPDE',
    question: '다음 중 IPDE-I에 대한 설명으로 가장 적절한 것은?',
    choices: ['Interpret', 'Inspect', 'Identify', 'Integrate'],
    answer: 2,
    explanation: 'IPDE는 Identify-Predict-Decide-Execute.',
    source: '기출·신경향',
  },
  {
    id: 81, part: 3, partName: '운전행동', grade: 'A', topic: 'IPDE',
    question: '다음 중 IPDE-P에 대한 설명으로 가장 적절한 것은?',
    choices: ['Protect', 'Process', 'Plan', 'Predict'],
    answer: 3,
    explanation: 'P는 위험 예측 단계다.',
    source: '기출·신경향',
  },
  {
    id: 82, part: 3, partName: '운전행동', grade: 'A', topic: 'IPDE',
    question: '다음 중 IPDE-D에 대한 설명으로 가장 적절한 것은?',
    choices: ['Direct', 'Drive', 'Decide', 'Detect'],
    answer: 2,
    explanation: 'D는 대응방법 결정 단계다.',
    source: '기출·신경향',
  },
  {
    id: 83, part: 3, partName: '운전행동', grade: 'A', topic: 'IPDE',
    question: '다음 중 IPDE-E에 대한 설명으로 가장 적절한 것은?',
    choices: ['Estimate', 'Evaluate', 'Execute', 'Escape'],
    answer: 2,
    explanation: 'E는 결정한 행동 실행 단계다.',
    source: '기출·신경향',
  },
  {
    id: 84, part: 4, partName: '심리·동기', grade: 'A', topic: '매슬로우 욕구단계',
    question: '다음 중 매슬로우 5단계에 대한 설명으로 가장 적절한 것은? [2025.06 후기축]',
    choices: ['생리-사회-안전-자아실현-존중', '생리-안전-사회-존중-자아실현', '사회-안전-생리-존중-자아실현', '안전-생리-사회-자아실현-존중'],
    answer: 1,
    explanation: '대표 순서는 생리→안전→사회→존중→자아실현이다.',
    source: '기출·신경향',
  },
  {
    id: 85, part: 4, partName: '심리·동기', grade: 'A', topic: '캇츠 태도기능',
    question: '다음 중 캇츠-가치표현에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['자아방어', '자신의 가치와 자아개념을 표현·강화', '환경정보 조직', '보상 획득'],
    answer: 1,
    explanation: '가치표현 기능은 정체성과 가치관 표현이다.',
    source: '기출·신경향',
  },
  {
    id: 86, part: 4, partName: '심리·동기', grade: 'A', topic: '캇츠 태도기능',
    question: '다음 중 캇츠-도구적에 대한 설명으로 가장 적절한 것은?',
    choices: ['자아 보호', '환경 이해', '보상을 얻고 불이익을 피하려는 기능', '가치관 표현'],
    answer: 2,
    explanation: '도구적 기능은 효용·보상과 관련된다.',
    source: '기출·신경향',
  },
  {
    id: 87, part: 4, partName: '심리·동기', grade: 'A', topic: '캇츠 태도기능',
    question: '다음 중 캇츠-지식에 대한 설명으로 가장 적절한 것은?',
    choices: ['자아방어만', '환경과 정보를 조직하여 이해하려는 기능', '사회적 지위 표현만', '보상만 추구'],
    answer: 1,
    explanation: '지식 기능은 세상을 이해하고 예측하게 한다.',
    source: '기출·신경향',
  },
  {
    id: 88, part: 4, partName: '심리·동기', grade: 'A', topic: '캇츠 태도기능',
    question: '다음 중 캇츠-자아방어에 대한 설명으로 가장 적절한 것은?',
    choices: ['규범 준수만', '교재 조직', '불안·위협으로부터 자아 보호', '보상획득'],
    answer: 2,
    explanation: '자아방어 기능은 심리적 위협에서 자아를 보호한다.',
    source: '기출·신경향',
  },
  {
    id: 89, part: 4, partName: '심리·동기', grade: 'A', topic: '준거집단',
    question: '다음 중 준거집단에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['일시적 군중만', '사고조사팀', '개인의 태도·가치·행동 판단 기준이 되는 집단', '처벌집행 기관'],
    answer: 2,
    explanation: '준거집단은 자신을 평가하거나 행동기준으로 삼는 집단이다.',
    source: '기출·신경향',
  },
  {
    id: 90, part: 4, partName: '심리·동기', grade: 'A', topic: '내외적요인',
    question: '다음 중 내적 요인에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['날씨·도로상태', '조직규정·시설', '개인의 동기·태도·성격·능력 등', '차량결함만'],
    answer: 2,
    explanation: '개인 내부의 심리·생리적 특성이다.',
    source: '기출·신경향',
  },
  {
    id: 91, part: 4, partName: '심리·동기', grade: 'A', topic: '내외적요인',
    question: '다음 중 외적 요인에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['개인의 지각능력', '개인의 성격', '환경·조직·시설 등 개인 외부 조건', '개인의 동기'],
    answer: 2,
    explanation: '개인 외부에서 행동에 영향을 주는 조건이다.',
    source: '기출·신경향',
  },
  {
    id: 92, part: 4, partName: '심리·동기', grade: 'A', topic: '외부자극',
    question: '다음 중 외부자극에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['조직규정 자체만', '환경에서 감각기관으로 들어오는 정보', '성격 자체', '기억에서만 생성되는 정보'],
    answer: 1,
    explanation: '외부자극은 감각기관을 통해 유입되는 환경정보다.',
    source: '기출·신경향',
  },
  {
    id: 93, part: 2, partName: '조직·평가', grade: 'A', topic: '현혹효과',
    question: '다음 중 현혹효과에 대한 설명으로 가장 적절한 것은? [2025.06 후기축]',
    choices: ['한 특성의 인상이 다른 평가영역에도 영향', '무조건 후하게 평가', '자기특성 전가', '집단고정관념 평가'],
    answer: 0,
    explanation: '한 분야의 인상이 전체평가로 번지는 오류다.',
    source: '기출·신경향',
  },
  {
    id: 94, part: 2, partName: '조직·평가', grade: 'A', topic: '상동적 오류',
    question: '다음 중 상동적 오류에 대한 설명으로 가장 적절한 것은? [2025.06 후기축]',
    choices: ['자기특성 전가', '관련없는 항목 상관 인식', '소속집단의 고정관념에 따라 개인을 평가', '한 특성이 전체에 영향'],
    answer: 2,
    explanation: '개인보다 집단의 전형을 기준으로 평가한다.',
    source: '기출·신경향',
  },
  {
    id: 95, part: 2, partName: '조직·평가', grade: 'A', topic: '교통안전일반',
    question: '다음 중 투사에 대한 설명으로 가장 적절한 것은? [2025.06 후기축]',
    choices: ['한 특성으로 전체평가', '자기 자신의 특성이나 관점을 타인에게 전가', '집단 고정관념 평가', '무조건 후하게 평가'],
    answer: 1,
    explanation: '자기특성을 상대에게 있다고 보는 오류다.',
    source: '기출·신경향',
  },
  {
    id: 96, part: 2, partName: '조직·평가', grade: 'A', topic: '상관적 편견',
    question: '다음 중 상관적 편견에 대한 설명으로 가장 적절한 것은?',
    choices: ['자기특성 전가', '중앙점수만 부여', '관련 없는 평가항목 사이에 상관이 있다고 인식', '최근 사건만 평가'],
    answer: 2,
    explanation: '무관한 항목을 유사하게 평가하는 오류다.',
    source: '기출·신경향',
  },
  {
    id: 97, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 중 관대화 경향에 대한 설명으로 가장 적절한 것은?',
    choices: ['지나치게 엄격 평가', '최근 정보만 반영', '피평가자를 실제보다 후하게 평가', '중간점수만 부여'],
    answer: 2,
    explanation: '실제보다 높은 평가를 주는 경향이다.',
    source: '기출·신경향',
  },
  {
    id: 98, part: 4, partName: '심리·동기', grade: 'A', topic: '교수설계',
    question: '다음 중 교수설계 3단계에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['평가-분석-통제', '설계-운영-감사', '분석-설계-평가', '분석-실습-보상'],
    answer: 2,
    explanation: '후기에서 분석→설계→평가 순서가 반복 언급됐다.',
    source: '기출·신경향',
  },
  {
    id: 99, part: 4, partName: '심리·동기', grade: 'A', topic: '교수설계',
    question: '다음 중 교수설계 분석에 대한 설명으로 가장 적절한 것은?',
    choices: ['요구분석·직무분석·학습자분석', '성과급 지급', '시청각 매체 실제 제작', '강의실 배치만'],
    answer: 0,
    explanation: '분석단계는 교육요구와 대상·직무를 파악한다.',
    source: '기출·신경향',
  },
  {
    id: 100, part: 4, partName: '심리·동기', grade: 'A', topic: '교수설계',
    question: '다음 중 교수설계 설계에 대한 설명으로 가장 적절한 것은?',
    choices: ['교육 후 효과만 평가', '사고통계 폐기', '요구 최초조사', '목표·내용·방법·매체를 구체화'],
    answer: 3,
    explanation: '설계는 목표와 전략·매체를 구체화한다.',
    source: '기출·신경향',
  },
  {
    id: 101, part: 4, partName: '심리·동기', grade: 'A', topic: '교수설계',
    question: '다음 중 교수설계 평가에 대한 설명으로 가장 적절한 것은?',
    choices: ['교재 최초개발', '교육목표 달성도와 효과 확인', '대상 요구 최초조사', '조직도 작성'],
    answer: 1,
    explanation: '평가는 교육성과와 효과를 검증한다.',
    source: '기출·신경향',
  },
  {
    id: 102, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 중 집합교육에 대한 설명으로 가장 적절한 것은?',
    choices: ['1:1 멘토링만', '강의·토론·실습 등 다수 대상 교육', '개별 카운슬링만', '자기학습만'],
    answer: 1,
    explanation: '집합교육은 다수 학습자를 대상으로 한다.',
    source: '기출·신경향',
  },
  {
    id: 103, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 중 카운슬링에 대한 설명으로 가장 적절한 것은?',
    choices: ['대규모 강의', '기계고장분석', '개별 상담 중심 교육기법', '집합토론만'],
    answer: 2,
    explanation: '카운슬링은 개인상담 성격이 강하다.',
    source: '기출·신경향',
  },
  {
    id: 104, part: 2, partName: '조직·평가', grade: 'A', topic: '현장안전회의',
    question: '다음 중 현장안전회의에 대한 설명으로 가장 적절한 것은? [2025.08 후기축]',
    choices: ['위험예지-확인-도입-점검-운행', '도입-점검장비-운행지시-위험예지-확인', '도입-운행지시-위험예지-점검장비-확인', '확인-도입-위험예지-운행지시-점검'],
    answer: 1,
    explanation: '2025.08 후기에서 \'도점운위확\'으로 언급됐다.',
    source: '기출·신경향',
  },
  {
    id: 105, part: 3, partName: '운전행동', grade: 'A', topic: '고령자교통특성',
    question: '다음 중 노인 교통특성에 대한 설명으로 가장 적절한 것은?',
    choices: ['속도·거리 판단 정확도와 반응능력이 저하될 수 있음', '청년보다 감각기능 우수', '위험예측이 항상 높음', '반응시간이 항상 빠름'],
    answer: 0,
    explanation: '노화에 따라 지각·판단·반응능력이 저하될 수 있다.',
    source: '기출·신경향',
  },
  {
    id: 106, part: 3, partName: '운전행동', grade: 'A', topic: '교통안전일반',
    question: '다음 중 어린이 교통특성에 대한 설명으로 가장 적절한 것은?',
    choices: ['복잡한 상황처리 우수', '성인보다 거리판단 정확', '주의·판단이 미숙하고 모방행동이 나타날 수 있음', '감정에 따른 변화 없음'],
    answer: 2,
    explanation: '어린이는 인지·주의·판단능력이 충분히 성숙하지 않았다.',
    source: '기출·신경향',
  },
  {
    id: 107, part: 5, partName: '사고분석', grade: 'B', topic: '안전벨트',
    question: '다음 중 안전벨트 효과에 대한 설명으로 가장 적절한 것은?',
    choices: ['사고확률 0', '충격량 증가 목적', '충돌 시 탑승자 이탈과 2차 충돌 위험 감소', '반응시간 단축'],
    answer: 2,
    explanation: '대표적인 수동안전장치로 인명피해를 줄인다.',
    source: '기출·신경향',
  },
  {
    id: 108, part: 5, partName: '사고분석', grade: 'B', topic: '사고율',
    question: '다음 중 사고율 지표에 대한 설명으로 가장 적절한 것은?',
    choices: ['광고비만 기준', '조직원 수만 기준', '인구·차량대수·주행거리 등 노출량을 기준으로 산정', '차량가격만 기준'],
    answer: 2,
    explanation: '사고율은 사고발생을 노출량과 관계지어 비교한다.',
    source: '기출·신경향',
  },
  {
    id: 109, part: 5, partName: '사고분석', grade: 'B', topic: '사고율',
    question: '다음 중 노출량에 대한 설명으로 가장 적절한 것은?',
    choices: ['사고위험에 노출되는 교통활동의 크기', '사고후 보험금', '시설 건설비', '교육횟수'],
    answer: 0,
    explanation: '주행거리·통행량·차량대수 등이 대표적이다.',
    source: '기출·신경향',
  },
  {
    id: 110, part: 5, partName: '사고분석', grade: 'B', topic: '교통안전일반',
    question: '다음 중 시몬즈 사고비용에 대한 설명으로 가장 적절한 것은?',
    choices: ['보험비용과 비보험비용을 함께 고려', '사고건수만 합산', '보험료만 계산', '사망자수만 계산'],
    answer: 0,
    explanation: '시몬즈 방식은 비보험비용도 함께 본다.',
    source: '기출·신경향',
  },
  {
    id: 111, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 중 교통안전도 평가에 대한 설명으로 가장 적절한 것은? [2025.06 후기축]',
    choices: ['운임수입만 비교', '차량가격만 비교', '신호기 수만 비교', '복수의 사고·피해지표를 종합해 안전수준 비교'],
    answer: 3,
    explanation: '여러 안전성과 지표를 종합해 비교한다.',
    source: '기출·신경향',
  },
  {
    id: 112, part: 3, partName: '운전행동', grade: 'A', topic: '위험예측',
    question: '다음 중 위험예측 4단계에 대한 설명으로 가장 적절한 것은? [2025.06 후기축]',
    choices: ['발견-행동-종료-평가', '대책-발견-예측-행동', '행동-예측-발견-종료', '위험발견-위험예측-대책결정-행동실시'],
    answer: 3,
    explanation: '후기에서 위험예측 단계 순서 문제가 언급됐다.',
    source: '기출·신경향',
  },
  {
    id: 113, part: 2, partName: '조직·평가', grade: 'A', topic: '갈등해소',
    question: '다음 중 갈등해소-문제해결에 대한 설명으로 가장 적절한 것은?',
    choices: ['갈등 무시', '조직 해체', '상대 억압', '당사자들이 원인을 함께 분석해 해결안 탐색'],
    answer: 3,
    explanation: '공동으로 갈등 원인을 탐색하고 해결한다.',
    source: '기출·신경향',
  },
  {
    id: 114, part: 2, partName: '조직·평가', grade: 'A', topic: '갈등해소',
    question: '다음 중 갈등해소-상위목표에 대한 설명으로 가장 적절한 것은?',
    choices: ['당사자 완전분리', '조직해체', '집단들이 공동 달성해야 할 더 큰 목표 제시', '보상중단'],
    answer: 2,
    explanation: '공동 상위목표는 집단 간 협력을 유도한다.',
    source: '기출·신경향',
  },
  {
    id: 115, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '2025년 8월 합격후기에서 교통안전관리론 복원 PDF에서 많이 나왔다고 직접 언급된 묶음으로 가장 가까운 것은? [2025.08 후기축]',
    choices: ['4M·캇츠·교수설계·명순응/암순응·욕조곡선', '캔트·슬랙·침목·터널단면', '철도안전법 벌칙만', 'KTCS-3·CBTC만'],
    answer: 0,
    explanation: '2025.08 후기에서 해당 키워드들이 직접 언급됐다.',
    source: '기출·신경향',
  },
  {
    id: 116, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '최근 후기들을 종합한 학습전략으로 가장 적절한 것은?',
    choices: ['개념카드로 구조를 잡고 기출·복원을 반복하며 유사 선지까지 구분', '답 번호만 외우고 이론은 전혀 보지 않음', '수치 문제는 전부 버림', '관리론은 포기'],
    answer: 0,
    explanation: '반복축이 강하지만 신경향 선지변형 대비를 위해 개념 구분도 필요하다.',
    source: '기출·신경향',
  },
  {
    id: 117, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 설명과 가장 관련 깊은 개념은? 분석-설계-평가 [2025.08 후기축]',
    choices: ['집합교육', '중간관리자', '교수설계 3단계', '4M-Man'],
    answer: 2,
    explanation: '후기에서 분석→설계→평가 순서가 반복 언급됐다.',
    source: '기출·신경향',
  },
  {
    id: 118, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 설명과 가장 관련 깊은 개념은? 비교적 일정한 낮은 고장률 [2025.08 후기축]',
    choices: ['관리적 접근', '욕조곡선-우발고장기', '위험예측 4단계', '반응시간'],
    answer: 1,
    explanation: '정상 사용 중 우발고장은 비교적 일정하다.',
    source: '기출·신경향',
  },
  {
    id: 119, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 설명과 가장 관련 깊은 개념은? 환경·조직·시설 등 개인 외부 조건 [2025.08 후기축]',
    choices: ['4M-Machine', '동체시력 감소율', '외적 요인', '하인리히 도미노'],
    answer: 2,
    explanation: '개인 외부에서 행동에 영향을 주는 조건이다.',
    source: '기출·신경향',
  },
  {
    id: 120, part: 1, partName: '관리이론', grade: 'A', topic: '교통안전일반',
    question: '다음 설명과 가장 관련 깊은 개념은? 정지시력보다 약 30% 감소',
    choices: ['갈등해소-상위목표', '동체시력 감소율', '명·암순응 관계', '교수설계 3단계'],
    answer: 1,
    explanation: '공개 복원축에서 약 30% 감소가 반복된다.',
    source: '기출·신경향',
  },
];